# Use official Python image
FROM python:3.11

# Set working directory
WORKDIR /app

# Copy files into container
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt
RUN python -m spacy download en_core_web_sm

# Expose API port
EXPOSE 8080

# Start the Flask application
CMD ["python", "app.py"]
